### ISSUE TITLE
Hacer un .gitignore bueno, bueno, bueno....

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#11]
En [gitignore.io](https://www.gitignore.io/) puedes generar dinámicamente.

**Comment by ElenaMLopez** [comment]
Tipo esto? o es que quieres que te diga que y cómo meter?
XD
https://gist.github.com/ElenaMLopez/c8b1f9cf1eb59f79840495299242a9fe
