### ISSUE TITLE
Pueden dos objectos ser iguales?

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#14]
ejemplo a resolver:

```javascript
var a = {algo: "aaa"};
var b = {algo: "aaa"}
var sonIguales = {algo: "aaa"} === {algo: "aaa"}  // false

// Tu solución

console.assert(sonIguales === true, "Error! No son lo mismo... Buen intento! :-)")

```

**Comment by ElenaMLopez** [comment]
Si se funciona por asignación de referencia... a no ser que sean dos objetos distintos que apuntan al mismo lo veo complicao... 
```
var frutas = {tipo: 'fruta', cantidad: 1};
var frutillas  =  frutas;
var ricas  =  frutas;
frutillas  ===  ricas
```
Da verdadero porque tanto frutillas como ricas apuntan al mismo objeto, que ocupa su espacio propio en memoria. 
Creo q me he explicado.... XD

**Comment by k0sasp** [comment]
Lo que plantea Úlises, si no me equivoco, nunca te va a dar true, porque son dos objetos totalmente distintos, aunque tengan el mismo contenido son independientes, si por ejemplo tuviera en ambos objetos una propiedad que fuera nombre, la propiedad si la podría comparar, o sea el contenido de esta, pero dos objetos declarados de esta forma siempre van a ser independientes... Creo xD

**Comment by vmrodriguez95** [comment]
Estoy de acuerdo con @k0sasp, los objetos son dos instancias diferentes que entre sí, aunque el contenido sea igual, siempre va a ser diferente. Lo que @ElenaMLopez  hace no es igual a lo que comenta Ulises, está asignando un mismo objeto a dos variables diferentes que, al compararlas, obviamente son iguales. Yo no creo que haya ningún caso en que comparando dos objetos devuelva true.

**Comment by UlisesGascon** [comment]
@ElenaMLopez me compartió [este recurso](https://www.todojs.com/comparacion-objetos-javascript/) que explica bastante bien los problemas a la hora de comparar. Pero si queremos crear el mismo objeto simplemente podemos hacer uso de herramientas propias de los lenguajes de programación, en concreto, de los patrones.

Veamos como se puede resolver esto con la implementación de un [singleton](https://es.wikipedia.org/wiki/Singleton)

```javascript
    var miSingleton = (function () {
        var instancia;

        function crearInstancia() {
            var objeto = new Object();
            return objeto;
        }

        return {
            instanciacion: function () {
                if (!instancia) {
                    instancia = crearInstancia();
                }
                return instancia;
            }
        };
    })();

        // ¿Son lo mismo 2 objectos igaules?
        var instancia1 = {};
        var instancia2 = {};
        console.info("¿Es lo mismo? " + (instancia1 === instancia2));

        // ¿Son lo mismo 2 objectos si se instancian una unica vez?
        instancia1 = miSingleton.instanciacion();
        instancia2 = miSingleton.instanciacion();
        console.info("¿Es la misma instaciación? " + (instancia1 === instancia2));

        // ¿Si extendemos propiedades... siguen siendo lo mismo?
        instancia1.algo = "aaa"
        instancia2.algo = "aaa"
        console.info("¿Es la misma instaciación? " + (instancia1 === instancia2));

       // ¿Si extendemos propiedades distintas... siguen siendo lo mismo?
        instancia1.otraCosa = "otra cosa...."
        instancia2.algo = "hola"
        console.info("¿Es la misma instaciación? " + (instancia1 === instancia2));
       
        // ¿Si son destintos... pueden ser iguales a la vez?
       console.log(instancia1);
       console.log(instancia2);
```

**Comment by vmrodriguez95** [comment]
Vaaaaaaaaale ya lo pillo, dos objetos nunca serán iguales pero las instancias de un mismo objeto si que son iguales porque en realidad es el mismo objeto el que comparas consigo mismo.

**Comment by UlisesGascon** [comment]
:trollface: https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/blob/master/teoria/dia45.md#singleton
