### ISSUE TITLE
Conocéis alguna fuente donde encontrar APIs molonas para consumir?

### ISSUE THREAD

**Issue by felixrigau** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#15]
Hola a todos! me preguntaba si conocéis donde podemos encontrar APIs interesantes?

Pienso que nos sería útil poder conocer la mayor cantidad de APIs disponibles, pues nos servirían de  base e inspiración para generar buenas ideas para el próximo proyecto de la clase 25.

Si conocéis algunas fuentes de APIs o alguna API en particular que esté chula, por aquí nos las podríamos compartir.

Buen finde!

**Comment by felixrigau** [comment]
Aquí van dos que he encontrado:

1. [(https://github.com/toddmotto/public-apis)]

2. [https://any-api.com/]

**Comment by Vickysolo** [comment]
Aquí puedes encontrar un montón, ordenadas por categorías:

https://www.programmableweb.com/category-api

**Comment by UlisesGascon** [comment]
Creo que esto puede ayudar....

### Listado de APIs

- [Public APIs](https://github.com/toddmotto/public-apis)
- [programmableweb - List](https://www.programmableweb.com/apis/directory)
- [Open APIs Wikipedia](https://en.wikipedia.org/wiki/List_of_open_APIs)
- [apilist.fun](http://apilist.fun/)

### Utilidades

- [Import.io](https://www.import.io/)
- [Jsonviewer](http://jsonviewer.stack.hu/)
- [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop)

### APIs Interesantes

- [Shodan](https://www.shodan.io/)
- [pokeapi](http://pokeapi.co/)
- [Open Weather Map](http://openweathermap.org/)
- [Fitbit](https://dev.fitbit.com/eu)
- [Marvel](http://developer.marvel.com/)
- [SWAPI - The Star Wars API](https://swapi.co/)
- [reddit](https://www.reddit.com/dev/api)
- [Deck of Cards - API](http://deckofcardsapi.com/)
- [TheTVDB API v2](https://api-beta.thetvdb.com/swagger#/)
- [Twitter Streaming](https://dev.twitter.com/streaming/overview)
- [Guild Wars 2](https://api.guildwars2.com/v2)
- [Nutritionix API](https://www.nutritionix.com/business/api)


### Datos Abiertos

- [Portal de datos abiertos del Ayuntamiento de Madrid](http://datos.madrid.es/portal/site/egob/)
- [Iniciativa de datos abiertos del Gobierno de España](http://datos.gob.es/)
- [EMT Datos Abiertos](http://opendata.emtmadrid.es/)
- [European Data Portal](https://www.europeandataportal.eu/)
- [Open NASA](https://open.nasa.gov/open-data/)
- [Datos Abiertos de Mexico](https://datos.gob.mx/)
- [The home of the U.S. Government’s open data](https://www.data.gov/)
