### ISSUE TITLE
Añadir un upstream para un fork

### ISSUE THREAD

**Issue by inigojorcano** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#17]
https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by UlisesGascon** [comment]
![notas_github](https://user-images.githubusercontent.com/5110813/32508124-9aae02fa-c3e9-11e7-8727-4ddea0bbf2c7.png)
