### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#2]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos _issues_ nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by ElenaMLopez** [comment]
###Elena Mateos López:
Soy Adalaber y me he reinventado como programadora front recientemente. Estoy trabajando (y alucinando a diario) en BQ y muy feliz de haber encontrado una pasión de la que puedo vivir. Llevo poco camino recorrido y tengo un síndrome del impostor del tamaño de un mastodonte, pero no tengo miedo y me encanta TODO lo que veo, escucho y aprendo.

De formación universitaria filósofa y completamente admirada de la capacidad del ser humano de hacer (también) cosas geniales y buenas. 

La consola de linux me resulta terriblemente adorable, y, en ocasiones, experimento demasiado. Además los ordenadores siempre se asustan conmigo, y hacen cosas raras, pero luego acabamos entendiéndonos y llevándonos muy bien. 

Amante incondicional del Open Source, saco tiempo de las piedras para colaborar en lo que puedo. 

PD: No mires mi github, va en serio, lo tengo de pena. Espero que a final de curso tenga mejor aspecto je je je. 
Encantada de conoceros y de compartir este pedazo de máster con vosotr@s. Vamos a hacer cosas molonas!!! :muscle:

**Comment by txesus** [comment]
¡Hola!

Soy Jesús Esteban, vengo del mundo gráfico (Agencias de Publi, Periódicos, etc), llevo trabajando varios años en Liquid Squad, antigua Tecnilógica (Accenture) como Frontend, UX/UI.

Me apasiona a la fotografía, el diseño gráfico y las artes visuales sobre todo el videomapping.

Muchas ganas de empezar a trastear con JS y encantado de poder hacer este máster y hacerlo con gente tan maja como vosotros :-)

**Comment by felixrigau** [comment]
Hola equipo!!!

Soy Felix Pablo, soy ingeniero informático de profesión pero bastante desactualizado. Debido a que salí de Cuba junto a mi esposa, buscando nuevos horizontes y una vida más digna, hace un 1 y 8 meses que no desarrollo. Antes de llegar a Madrid hace 2 meses, viví en Lyon, Francia.

Durante la universidad pasé (o más bien sufrí :satisfied:) en el mundo de JAVA para la web con JSF ( y lo digo bajito como Carlos :stuck_out_tongue_winking_eye: ). Luego que me gradué, trabajé en una pequeña startup cubana ingeniuscuba.com, donde  aprendí de manera autodidacta el 80% de las tecnologías que conozco. Allí aprendí a maquetar pues fue mi principal tarea. También hice algo de SEO e incursioné en el diseño gráfico orientado a la web. El diseño gráfico es otra cosa que me apasiona un montón, soy muy visual. 

La próxima semana comenzaré a trabajar como berario en Kelisto.es, allí me han propuesto formar parte del team de desarrollado y desarrollar con Ruby on Rails, tecnologías que no conozco pero MEJOR AÚN! MÁS TECNOLOGÍAS POR DESCUBRIR!

Este inicio de máster me he sentido como un niño pequeño que empieza a descubrir el mundo. Las clases las comparo con la primera clase de un idioma del cual tienes alguna noción: A VECES ENTIENDO ALGUNAS PALABRAS... :flushed: :laughing: . Pero así es mejor, pues eso implica retos y eso me motiva muchísimo.

Este máster tiene muchos significados para mi:
Una inversión profesional y familiar.
Darme una segunda oportunidad en mi profesión.
La posibilidad de hacer varios proyectos presonales que tengo en mente.
El resultado de mucho tiempo de discernir a donde iba a reorientar mi futuro profesional.
Realizar el sueño de ser un ninja :satisfied: en Javascript.

Se que este año va a ser genial, que formaremos un buen equipo y que junto a vosotros viviré algo que marcará un antes y un después en mi vida personal y profesional.

Disculpen el editoral :satisfied:
Nos vemos luego!

Ah! otra cosa, me encantá el ciclismo de carretera, hacer kilometros y kilómetros sobre una bici, o subir montañas, es algo que me despeja totalmente la mente y lo disfruto cantidad.

**Comment by vmrodriguez95** [comment]
Buenas!!

Yo me llamo Víctor, llevo trabajando como programador casi tres años. Empecé, junto con Iñigo, el grado superior de Desarrollo Multiplataforma y a la par trabajabamos para una startup donde descubrimos el maravilloso (o quizás no tan maravilloso para algunos) mundo del front. Aprendimos a manejarnos con algunos lenguajes y coger algo de soltura en cuanto a la programación. Según acabamos este grado superior decidimos hacer el de Web para empezar a orientarnos un poco más hacia el front.

Hoy en día me propongo muchos retos, uno de ellos es dominar Javascript ya que creo que es el lenguaje que durante muchos años va a estar en la cima, y aprender cosas nuevas, como Node.js.

En cuanto a mis gustos personales diré que soy un gran aficionado a los coches, al buen fútbol (tanto verlo como jugarlo) y a las cervezas con los amigos.
