### ISSUE TITLE
Codemotion 2017

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#29]
![](http://www.panel.es/wp-content/uploads/2016/10/codemotion-999x4991.jpg)

**[Agenda](https://2017.codemotion.es/agenda.html)**

**Comment by ValKiriann** [comment]
[agenda codemotion v5 finale.pdf](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/files/1499353/agenda.codemotion.v5.finale.pdf)
Adjunto agenda de los super recorridos
