### ISSUE TITLE
Birras de #memezinga

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#88]
Responde con...
V 15/06 -> 😆 
V 22/06 -> ❤️ 
V 29/06 -> 🎉 
ninguna -> 👎 
si puedes venir a cañas después de las 19h :-)

**Comment by ValKiriann** [comment]
🎉

**Comment by txesus** [comment]
Yo solo puedo el 30/06 :-(

**Comment by ValKiriann** [comment]
El 29 entonces finalmente no ?

**Comment by UlisesGascon** [comment]
eso parece @ValKiriann !
