### ISSUE TITLE
Robot de telegram

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#92]
- https://github.com/hosein2398/node-telegram-bot-api-tutorial
- https://github.com/yagop/node-telegram-bot-api
- https://github.com/request/request

**Comment by UlisesGascon** [comment]
![captura de pantalla 2018-06-13 a las 18 48 26](https://user-images.githubusercontent.com/5110813/41365709-68b13e96-6f3a-11e8-9f29-fadc494da1b3.png)

**Comment by ValKiriann** [comment]
👉 https://github.com/ValKiriann/spicy 
💣BOM! 💣
you can close this

**Comment by ValKiriann** [comment]
close #92
