### ISSUE TITLE
postMeesage

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1#99]
[turbio-y-peligroso.zip](https://github.com/Fictizia/Master-en-programacion-de-aplicaciones-con-JavaScript-y-Node.js_ed1/files/2150139/turbio-y-peligroso.zip)

**Comment by ValKiriann** [comment]
Cierro esta shit que jamás en la vida lo tocamos eh ?
